### ISSUE TITLE
CITATION.cff

### ISSUE THREAD

**Issue by eggplants** [akamhy/waybackpy#165]
[GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#about-citation-files) says:

> You can add a CITATION.cff file to the root of a repository to let others know how you would like them to cite your work. The citation file format is plain text with human- and machine-readable citation information.

CFF Schema Reference:
https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md

CFF Schema:
https://github.com/citation-file-format/citation-file-format/blob/main/schema.json

CFF Generator:
https://citation-file-format.github.io/cff-initializer-javascript

**Comment by eggplants** [comment]
```yml
cff-version: 1.2.0
title: waybackpy
version: 3.0.5
message: 'If you use this software, please cite it as below.'
type: software
authors:
  - given-names: Akash Mahanty
    name-particle: Akash
    family-names: Mahanty
    name-suffix: Mr.
    email: akamhy@yahoo.com
    affiliation: ... blur blur blur ...
```
